[package]
name = "pswd"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-clipboard = "0.4.0"
clap = { version = "4.4", features = ["cargo", "derive"] }
rand = "0.8.5"
